[2023-05-13T19:03:30.711+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hypothesis1.select_rows manual__2023-05-13T19:03:18.134960+00:00 [queued]>
[2023-05-13T19:03:30.737+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hypothesis1.select_rows manual__2023-05-13T19:03:18.134960+00:00 [queued]>
[2023-05-13T19:03:30.740+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-13T19:03:30.782+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): select_rows> on 2023-05-13 19:03:18.134960+00:00
[2023-05-13T19:03:30.796+0000] {standard_task_runner.py:57} INFO - Started process 459 to run task
[2023-05-13T19:03:30.805+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hypothesis1', 'select_rows', 'manual__2023-05-13T19:03:18.134960+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_hypothesis1.py', '--cfg-path', '/tmp/tmpfvfs4m_y']
[2023-05-13T19:03:30.812+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask select_rows
[2023-05-13T19:03:30.929+0000] {task_command.py:410} INFO - Running <TaskInstance: hypothesis1.select_rows manual__2023-05-13T19:03:18.134960+00:00 [running]> on host 9a745d3878c0
[2023-05-13T19:03:31.140+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hypothesis1' AIRFLOW_CTX_TASK_ID='select_rows' AIRFLOW_CTX_EXECUTION_DATE='2023-05-13T19:03:18.134960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-13T19:03:18.134960+00:00'
[2023-05-13T19:03:31.149+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_hypothesis1.py", line 17, in select_rows_py
    df = pd.read_csv('used_cars_data.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'used_cars_data.csv'
[2023-05-13T19:03:31.176+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=hypothesis1, task_id=select_rows, execution_date=20230513T190318, start_date=20230513T190330, end_date=20230513T190331
[2023-05-13T19:03:31.206+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 16 for task select_rows ([Errno 2] No such file or directory: 'used_cars_data.csv'; 459)
[2023-05-13T19:03:31.260+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-13T19:03:31.309+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
